### ISSUE TITLE
Warning about overwriting method

### ISSUE THREAD

**Issue by jhasse** [JuliaGL/ModernGL.jl#17]
```
Warning: Method definition getprocaddress(ASCIIString,) in module ModernGL at /home/jhasse/.julia/v0.4/ModernGL/src/ModernGL.jl:40 overwritten in module Main at /home/jhasse/git/clewer/src/opengl.jl:8.
```

I don't know if this is fixable, but it would be nice to get rid of the warning ;)

**Comment by SimonDanisch** [comment]
Hi,
do you really need to overwrite getprocaddress?

Best,
Simon

**Comment by jhasse** [comment]
Oh you're right, it's also working without me doing it. I thought it was needed. Maybe on Windows? I will test later on.

**Comment by SimonDanisch** [comment]
If you followed the suggestion from the README.md, chances are that you
don't need this.
When I wrote this, I wasn't sure, if everything can be handled by a generic
getproccaddress. So far, there haven't been any case where the
getproccaddress supplied by ModernGL wasn't sufficient.

2015-01-26 14:30 GMT+01:00 Jan Niklas Hasse <notifications@github.com>:

**Comment by jhasse** [comment]
Just tested it on Windows and it's indeed not needed :)
