### ISSUE TITLE
API

### ISSUE THREAD

**Issue by lucagessi** [JuliaGL/ModernGL.jl#41]
I. I would like to use this library but I don't know where to find any row of API. Is there something to read?

Thanks

**Comment by SimonDanisch** [comment]
row of API? this is 1:1 opengl, so you use it exactly like any opengl code and can therefore use any OpenGL documentation: https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf

You might want to check:
https://github.com/JuliaGL/GLAbstraction.jl/tree/master/tutorials
https://github.com/JuliaGL/GLAbstraction.jl/tree/master/example
https://github.com/JuliaGL/GLVisualize.jl
https://github.com/SimonDanisch/MakiE.jl

**Comment by Gnimuc** [comment]
FYI, I ported some examples of [Anton's OpenGL 4 Tutorials](http://antongerdelan.net/opengl/) here: https://github.com/Gnimuc/Videre/tree/master/OpenGL%204%20Tutorials
