### ISSUE TITLE
Update to OpenGL 4.6

### ISSUE THREAD

**Issue by holocronweaver** [JuliaGL/ModernGL.jl#42]
I notice that a number of functions from GL 4.5 (e.g. `glCreateSamplers`) and 4.6 (e.g. `glMultiDrawArraysIndirectCount`) are missing.

I'd like to go ahead and update the bindings for GL 4.6. 

Are wrappers generated from a script via GL C headers, or is wrapping done manually?

**Comment by SimonDanisch** [comment]
That'd be great! I think they were done semi automatically with some regex/string transformation code.. The script probably got lost, but if it's anywhere it should be here: https://github.com/JuliaPackageMirrors/OpenGL.jl

**Comment by CarpeNecopinum** [comment]
That would be pretty cool indeed. Just noticed that `glBlitNamedFramebuffer` (GL 4.5) is missing as well.

Is there any progress towards this yet? Might consider helping with this myself.

**Comment by holocronweaver** [comment]
@CarpeNecopinum No progress on my side. Feel free to have at it.

**Comment by musm** [comment]
closed by https://github.com/JuliaGL/ModernGL.jl/pull/68
