### ISSUE TITLE
use const Refs instead of mutable structs

### ISSUE THREAD

**Issue by thraen** [JuliaGL/ModernGL.jl#61]
Hi!

Thanks for the repo!

While profiling, I found that all calls to gl function wrappers allocate a bit of memory. The allocation seems to come with the pointer wrapper type `GLFunc`. 

I found that there is no allocation when const Refs are used to store the pointers.

I tested this a bit in a branch, it actually seemed to speed up my code a bit. If you're interested, I can make a pull request.

**Comment by SimonDanisch** [comment]
Cool sounds good to me :) This code is super old, so not surprising that something may have changed.

**Comment by thraen** [comment]
Yes, I could have sworn that the amount of allocation due to the structs changed between 1.2 and 1.4. .. Anyways :)   #62

**Comment by thraen** [comment]
The merge request seems to fail because of unrelated CI problems? Is there something I can do?

**Comment by SimonDanisch** [comment]
I guess I'd mainly just want to test this on Makie, and if that works fine merge & tag it ;)
